### ISSUE TITLE
ban explanation

### ISSUE THREAD

**Issue by nicholasf** [polyhack/helloworld#14] opened 2015-03-26 18:38 UTC
Hey,

A brief explanation about banning dibblego.

I talked through my reasons with wolfeidau. It wasn't a quick decision. It's accurate to say that it has been based over weeks rather than days.

The simplest way to put it is that he has often come into channel wanting to begin a fight. He obviously has a passion to teach Haskell. 

Another major aspect is that we are a polyglot community and he has continually derided programmers who use languages that don't match his preference. This wasn't a fit for the ideas based about why we formed. Nor is the channel a classroom to assume levels of status and attitude toward others as to whether they classify as a student or a teacher. 

We are a community of geeks, intellectuals, hackers, professionals, students; programmers who want to invest time learning and discussing ideas. We will probably have a lot of eccentric characters in our midst who want to defy social rules and will object to heavy rulesets.

But we do need a shared mode of collegial conduct ...

Tolerance and respect are qualities that are important in how we address the programming passions of others in the channel; whether someone is a beginner or an expert.

Best,
nicholasf

**Comment by kvanberendonck** [comment] 2015-03-26 20:47
Primarily as a Haskell programmer, I really don't know how to think about this.

It looks a lot like a lynching.

**Comment by SomeoneWeird** [comment] 2015-03-26 21:09
Nope, not cool.

You agreed when you registered the channel that we would only ban people who are intentionally spamming or being way out of line, or at least consult the rest of the channel in the case it was something else. I don't see either of those things happening here. I guess that's why you didn't want to appoint many other ops.

**Comment by mipearson** [comment] 2015-03-26 21:20
Nope. He mostly fought with you.

**Comment by andys** [comment] 2015-03-26 21:30
This may have a chilling effect on free speech

**Comment by mipearson** [comment] 2015-03-26 21:34
I was worried that this would happen - but I was worried that it would happen if we tried to have some sort of "ops rota" - and I felt that keeping it simple would also keep the ops role solely for "obvious" cases, eg spammers & bots.

I don't agree with him, but I agree with this much less, and I'll be out of the channel for a while as I'm mostly on there during work hours, and I don't need that kind of distraction. I had enough of that - and this feels very much like - the IRC "politics" of when I was a teenager.

**Comment by DamonOehlman** [comment] 2015-03-26 21:40
I'm glad to see other people's reactions to the ban align closely to my own here.  I haven't been following events over the last few days as I only even intermittently touch base with the channel.  Banning Tony is a big backwards step for the polyhack channel (and community), and unfortunately that damage has already been done.

I could go into depths and cover why Tony is an asset to any community he participates in.  Yes he's a thorny individual, but also a person that cares more about people and programming than just about anyone else I've ever met.

**Comment by radar** [comment] 2015-03-26 21:41
This sets a pretty bad precedent. If people disagree with each other in the channel are we going to ban them because they're being antagonistic? So what if someone has an opposite opinion to your own? There is no harm in that.

**Comment by mipearson** [comment] 2015-03-26 21:51
also because it's not a GH thread without gifs:

![wat](http://media.tumblr.com/5fa5fccf136ce92cff3ed6bacc8461bc/tumblr_inline_n3crcfgRNd1s4v4p9.gif)

**Comment by deoxxa** [comment] 2015-03-26 22:00
This is very uncool. Nobody has the right to "choose" whether someone else fits in or not. We've never had a problem that resulted in pushing someone out, unless they were overtly abusive. There's only one time that I can think of, and that was objectively the right move (user was flooding with abusive messages). This is so, so different to that, and really seems like a difference in personalities between Nicholas and Tony.

Politics is bullshit, @nicholasf, and you can't un-ring that bell now. You've introduced the concept of being forced out for holding opinions that differ from others'. This is a concept that didn't exist in this group, but that now does.

**Comment by mipearson** [comment] 2015-03-26 22:09
I propose that @nicholasf transfer ops to @wolfeidau and un ban Tony.

You fucked up big and this is the only way out I can see.

**Comment by kvanberendonck** [comment] 2015-03-26 22:21
This relates to the decision made in #10.

**Comment by nicholasf** [comment] 2015-03-26 23:03
@mipearson I spoke to @wolfeidau before doing this. Twice. He agrees with me.

**Comment by SomeoneWeird** [comment] 2015-03-26 23:11
@nicholasf was dibblego at least consulted before this decision was made? Ops are supposed to be catalysts when making decisions, and not involve personal feelings. You have still yet to address other questions bought up in this thread, too.

**Comment by mipearson** [comment] 2015-03-26 23:13
Ah, I thought you'd spoken after the fact. Things makes a little more sense.

**Comment by mipearson** [comment] 2015-03-26 23:18
Revising my opinion (ie, changing my mind, ie, something that politicians don't do): I interpreted this as a solo decision, but as a joint decision I'm much more open to it.

I still think it sets a worrying precedent but I'm a lot less negative about it than I was earlier. My apologies to @nicholasf for my aggressive initial reaction.

**Comment by mwotton** [comment] 2015-03-26 23:37
I think this is a terrible idea, and mostly personal. I'm very disappointed.

**Comment by davidmason** [comment] 2015-03-26 23:38
This whole issue looks like the discussion that I would have expected to happen before a decision was made. When I read:

> * ops should never be used against a member of the channel. I think this would be the circumstance where it might be abused. If this ever had to happen there would need to be a conversation about it.

in https://github.com/polyhack/helloworld/issues/10#issuecomment-58301931 I interpreted it to mean that there would be a conversation that all the regular members of the channel have a chance to take part in. In hindsight I guess two people talking to each other twice also fits the definition of a conversation.

For future non-urgent bans, I propose the following process:

1. Create an issue here with reasonable details about the proposed ban.
  - I would expect this to include chat logs, and to refer to a specific community guideline or guidelines that are not being adhered to.
  - This presumes the guidelines are written down somewhere. If they are not, the issue discussion should include getting them added to whatever document they are written on - that should happen before any ban goes ahead.
2. Kept the issue open until most regular members have had input and a general consensus is reached, and the relevant guidelines have been agreed upon and recorded if they were not already.
3. Decide whether to go ahead with a ban. If general agreement cannot be reached on whether the ban is appropriate, the rule should be to err on the side of not banning.

**Comment by DamonOehlman** [comment] 2015-03-26 23:41
+1 for @davidmason's recommended path forward.

**Comment by vacri** [comment] 2015-03-26 23:41
Just a comment from the sidelines (as the github emails keep ticking in). I'm not clear on the particulars of the event, but the commentary here is following a particular 'cleanup' pattern, though it does appear to be cooling a little.

Keep the commentary cool and calm. Humans are subject to emotions, and people make mistakes or have different readings of rules. Use this as an opportunity to clarify what we want ops to do in future.

**Comment by nicholasf** [comment] 2015-03-26 23:41
Guys, I'm in a day long meeting. We're revising our architecture completely.

I'll catch up with commentary when the day ends. 

For my mind I'm thinking that if dibblego is going to stay, I might leave. Not as an ultimatum but because the channel culture isn't running in a healthy way. Which is okay, perhaps that's how things work in online communities.

And, yeh, it isn't a quick decision or something that I was willing to act on without getting go ahead from @wolfeidau .

**Comment by mipearson** [comment] 2015-03-26 23:46
@nicholasf I don't think that's true - I think it goes through phases of talking about particular languages depending on who's there. There's been _lots_ of arguments, not only about haskell versus not-haskell. 

I remember when it was 24/7 node-bloody-js.

**Comment by mwotton** [comment] 2015-03-27 00:35
I would like to suggest that the ban should be revoked, pending an actual discussion and vote. I don't mind bending to the will of the community, but doing this without public consultation for someone who is not obviously spamming is unacceptable.

**Comment by zachgoldstein** [comment] 2015-03-27 00:43
+1 mwotton.

**Comment by nicholasf** [comment] 2015-03-27 01:49
I like the discussion on this ticket.

I'm going to take a while to think about things. There were a list of things I wanted from a polyglot community when I invited people into it and I see dibblego's behaviour as antithetical to it. 

I think building a guideline's document is a mistake. Then it becomes a matter of being litigious about rules, etc., and for the most part the channel functions well. @wolfeidau mentioned it as an idea in our discussion last night.

But the community is much bigger now. Lately I haven't been enjoying it at all. I invited a lot of you in and built it, but perhaps it's time I let it evolve and stop organising for the channel. This can include stepping aside as founder, etc..

I find dibblego's behaviour to be extreme and very subjective. I think he is promoting a contempt for other languages which made me leave the roro channel when I wanted to talk about node.js. I know for a fact it has insulted people in the channel. He has a history of being banned from other communities, too - which may be beside the point here, but he is an extreme personality.

I think a big point going on here is that people don't want an ops scheme that functions behind the scenes and is authoritarian. I agree in principle with that, but I don't see many ways forward really. 

When we did register the channel I specified ops would never be used against members of the channel. Dibblego has never had his name added to the github core list or the website membership. The reason I immediately shared founder status with @wolfeidau and opped @damncabbage when the channel was officially registered was to (a) share authority and (b) show that authority was not given out based on the amount of time someone had spent in the channel.

Before the channel was registered, the only thing I could do was explain to someone what bad behaviour was and hope people adopted it. This worked sometimes but not others. 

So, yeh, we can take some time to think here. I think a lot of the replies above don't see the real problems that @wolfeidau and I have reacted to. Perhaps you don't spend as much time thinking about how to make the channel work (and it has worked for three years). Perhaps, also, it's time to radically change how it runs. The way it has been running lately is not the channel I wanted to build years ago.

Cheers,
Nick

**Comment by wolfeidau** [comment] 2015-03-27 01:50
I am also of the opinion that dribblego chill for a while outside the channel, /ignore doesn't make it any better for new people.

To date people have been for the most part respectful of others views, and in general polite and friendly, this is one of the reasons I am in the channel. 

We all have opinions, debate and discussion in channel has "mostly" been civil.

It however goes without saying that derogatory remarks about other people in channel, especially insinuating they are "dumb" or "incompetent" because the don't agree with x, or don't use y, is never be OK. Call it what you like it is abuse.

I have nothing against dribblego personally, but I do think he does need to take a long hard look at how he is behaving online.

Pretty much with @nicholasf on this, if abuse is OK in #polyhack then i am out.

Note, my initial suggestion was to put up a code of conduct before doing anything.

Lastly I am no angel in this area as well, i get on my high horse from time to time, that said I "mostly" know when to shut up and listen for a while.

**Comment by davidmason** [comment] 2015-03-27 02:10
> There were a list of things I wanted from a polyglot community...

@nicholasf is it a secret? If not, what purpose is served by not writing down the things that you want for the community? You are writing things here, and I am sure someone reading through all the issues and chat logs could figure out the expected level of discourse and tone, but burying information about expected behaviour just makes it harder for new members to get up-to-speed.

There is a reason to call them guidelines, and they in general should be worded in an open way. They should capture the spirit of what is expected and what is considered unacceptable, they don't have to be specific enough that someone would be banned or not banned just on a technicality.

> promoting a contempt for other languages

I don't see any controversy in including this sentiment somewhere that new people will read it.

 -  #polyhack is specifically a polyglot group, so it is not acceptable to promote contempt for specific programming languages.

**Comment by mipearson** [comment] 2015-03-27 02:11
Too heavy.

**Comment by mwotton** [comment] 2015-03-27 02:14
@wolfeidau Could you be a bit more specific about what you mean by "abuse"? I checked my logs, he hasn't ever said "dumb", and he said "incompetent" once. Some of the discussions are robust, but there's been no more personal abuse than is the background level here, like ragging on @SomeoneWeird because he's young, or making fun of me because I use Haskell.

**Comment by davidmason** [comment] 2015-03-27 02:20
> It however goes without saying that derogatory remarks about other people in channel, especially insinuating they are "dumb" or "incompetent" because the don't agree with x, or don't use y, is never be OK. Call it what you like it is abuse.

@wolfeidau it does go without saying, but it could be said anyway. Someone who just wants to insult people might just not join the channel in the first place, and for someone who is apprehensive about joining a new channel it might be the assurance they need about how they should expect to be treated.

 - Derogatory remarks about other people in channel, especially insinuating they are "dumb" or "incompetent" because the don't agree with x, or don't use y, is never acceptable.

**Comment by davidmason** [comment] 2015-03-27 02:25
@mwotton this is why I propose getting guidelines recorded somewhere, and including chat logs in the issues for proposed bans - as a basis for everyone to reach a common agreement about what is unacceptable, then  to establish transparently what the instance or instances of the unacceptable behaviour are. People are a lot less likely to be confused about a ban if there is information that concisely says "Look here, this person is doing this thing that we all agree is unacceptable, and they won't stop doing it!"

**Comment by mwotton** [comment] 2015-03-27 02:37
@davidmason sounds good.

**Comment by radar** [comment] 2015-03-27 03:19
My bot (helpa) has been logging the channel publicly: http://logs.ryanbigg.com/polyhack.

**Comment by lukebakker000** [comment] 2015-03-27 03:30
I think @davidmason has the right idea.

**Comment by michaelneale** [comment] 2015-03-27 07:45
disappointed. Clearly this channel is too big and not for me.

**Comment by nicholasf** [comment] 2015-03-28 20:58
Ok. Moving forward.

Dibblego is banned for one month. The channel has been running with a system - I followed it to determine this decision. We will keep to it, whether or not it is popular.

We should improve the system. People have mentioned a code of conduct, so let's set one of those up. I would personally prefer if it conveyed an ethos and wasn't a rulebook. I would also like to discuss how we define membership and how it works for us.

**Comment by nicholasf** [comment] 2015-03-28 21:36
To get this started, here's what I suggest.

1) We elect three people to handle all polyhack matters for 1 year. Those three people can make decisions for the channel; they can maintain the membership list and the website, they can organise polyhack social events. @wolfeidau and I will op them but won't otherwise act for the channel.

2) People who are on the core list at github get to vote. If they aren't there, no vote.

3) We define a code of conduct so people new to the channel can understand what is required of their social behaviour.

The idea is that we evolve our membership so the most active people in the channel control how it runs. There will be mistakes but we'll work them out as they arrive.

**Comment by SomeoneWeird** [comment] 2015-03-28 23:08
For starters, I'm very disappointed that none of the questions that have been raised in this issue have been answered. 

1) I highly, highly disagree with "3 people can do anything", this will lead to this exact same issue, where people can dictate what happens because they have "power". I see this happen way too often in other larger IRC channels.

2) I have no problem with this, but I do have a problem with only 3 people in the owners team being active in the channel, maybe add a couple more just in case something happens?

**Comment by SomeoneWeird** [comment] 2015-03-28 23:09
Also, for what it's worth, while you were out, none of the people in the channel had a problem with dibblego staying. He was very civil about it.

**Comment by nicholasf** [comment] 2015-03-28 23:12
What are the questions?

**Comment by SomeoneWeird** [comment] 2015-03-28 23:14
https://github.com/polyhack/helloworld/issues/14#issuecomment-86729298
https://github.com/polyhack/helloworld/issues/14#issuecomment-86750221
https://github.com/polyhack/helloworld/issues/14#issuecomment-86789108
https://github.com/polyhack/helloworld/issues/14#issuecomment-86789371

**Comment by nicholasf** [comment] 2015-03-28 23:27
Right. 

So to Radar's point about precedence, this wasn't a ban due to personal disagreement. Dibblego's behaviour was antisocial and damaging to friendly discussion about a range of programming languages. How do we deal with people who have opposite opinions? Like we normally do; this is the first ban we've put in place to deal with this problem. We have a lot of precedents for dealing successfully with arguments.

For s1w's question. I warned dibblego *twice* about his behaviour in channel. I was thinking about asking blackdog to talk to him the night before we banned him. I wanted to see if blackdog could even see them problem with dibblego's behaviour. After the discussion with Mark Wolfe it was obvious to me that dibblego's behaviour wasn't good for the channel so I banned him.

For @davidmason 's question about the values of a polyglot channel, I'd like to evolve that in #16 - but they would include an idea that the channel is a space where different ideas should be respected. The problem with dibblego is that he would (a) flood the channel with his talk and (b) would insult people a lot of the time as he did it. This wasn't conducive to discussion and frustrated a lot of people.

I'm behind the guidelines idea now. At first I wasn't. 

For @mwotton 's question about clear about abuse; if he can't see that dibblego's attitude and approach to talking in channel is problematic, there's not a lot to be gained by pointing out individual moments of behaviour.

Lastly, what I'm suggesting in #16 means that anyone who wants to shape the culture of the channel can become active in doing so. There is work involved in running the channel - that needs to be shared out too.

**Comment by SomeoneWeird** [comment] 2015-03-28 23:36
Okay so what dibblego was doing was not "flooding" the channel, he was very expressive, sure, but if you want to see flooding, join a channel like #ubuntu or #bitcoin. It just doesn't seem like you have a lot of experience managing an IRC channel.

I'll just leave this here.

> \<dibblego\> hello, I am here because I woke up this morning to a private message from nicholasf telling me that "it was a group decision to ban me from this channel", but, I looked and I was still in the channel and I am told, that's because someone set the wrong twiddledy-do. In any case, I am disappointed that after scrolling back, the elephant still remains, nice and fat, in the room.

I think I will have to take a break from polyhack for a while, seeing as this issue is still not resolved.

**Comment by nicholasf** [comment] 2015-03-29 00:08
Taking a break can be healthy. 

I think it's important to recognise that dibblego's behaviour is poor form and he has a very visible history of it online in other communities. That, of course, is not a reason for banning him from #polyhack but it strengthens the argument that there are fundamental problems with his behaviour that others have recognised time and time again. 

Lastly, I think we should use this to clarify how things work - which is the purpose of #16. I would be very glad for some kind of small group to operate beneath a code of conduct and to handle community matters. This should definitely be shared out.

**Comment by tonymorris** [comment] 2015-03-29 00:23
Hello, this unfortunate issue that has been created by a very small number of people is unlikely to be resolved by using the usual mechanisms. Specifically, by ignoring those individuals and their counter-productive conduct and simply moving on with useful discussion (as is exemplified, once again, in the most recent episode).

As a consequence, I suggest using a different IRC channel for open discussion without the high-falutin posturing and incompetence. Fortunately, this is limited to only a very small number of individuals. On the other hand, I have found some people in the #polyhack channel to be excellent individuals, looking to share and discuss ideas openly without any other motivations. I am not (yet) willing to give this up, despite the apparent downsides, therefore, I look forward to suggestions in this regard.

Please don't "take a break." Tackling this kind of nonsense is important and is itself, a great learning opportunity.

PS: the ban is now in place on #polyhack

**Comment by tonymorris** [comment] 2015-03-29 00:28
For what it is worth, I was initially told that this was a "group decision." Knowing the cowardice in front of me, I thought nothing of it. This was (another) obvious falsehood (borne out of incompetence, not malice) in my at-the-time-private opinion.

However, since other individuals have expressed interest, here is everything I was told:

    Mar 27 08:43:32 <nicholasf>     [04:41:12] it was a group decision to ban you, sorry: https://github.com/polyhack/helloworld/issues/14
    Mar 27 08:44:30 <dibblego>      you are a coward

Times are in UTC+10.

**Comment by tonymorris** [comment] 2015-03-29 00:31
OK, so now @nicholasf is deleting my commentary. Discussion is over.

**Comment by tonymorris** [comment] 2015-03-29 00:33
I strongly suggest starting a new IRC channel where we can have open discussion. Please suggest a way by which we can achieve this. Please do not "take a break."

**Comment by tonymorris** [comment] 2015-03-29 00:38
For what it is worth, I was initially told that this was a "group decision." Knowing the cowardice in front of me, I thought nothing of it. This was (another) obvious falsehood (borne out of incompetence, not malice) in my at-the-time-private opinion.

However, since other individuals have expressed interest, here is everything I was told:

> Mar 27 08:43:32 <nicholasf>     [04:41:12] it was a group decision to ban you, sorry: https://github.com/polyhack/helloworld/issues/14
> Mar 27 08:44:30 <dibblego>      you are a coward

Times are in UTC+10.

**Comment by nicholasf** [comment] 2015-03-29 00:47
So, yeh, I've deleted tony morris' comments from this issue. 

I'm becoming very tired of this. If he wants to add more after this, he can. He is suggesting that you start a new IRC channel. I would encourage you to explore this option. It may make everyone happy. But leave it out of here please.

**Comment by tonymorris** [comment] 2015-03-29 00:51
I am not tired of it and I will fight hard to achieve open discussion, even if just for my own benefit. There are good people on the sideline of this ridiculous conduct of just a few petty individuals and I will fight for that purpose too.

**Comment by tonymorris** [comment] 2015-03-29 00:52
For what it is worth, I was initially told that this was a "group decision." Knowing the cowardice in front of me, I thought nothing of it. This was (another) obvious falsehood (borne out of incompetence, not malice) in my at-the-time-private opinion.

However, since other individuals have expressed interest, here is everything I was told:

    Mar 27 08:43:32 [04:41:12] it was a group decision to ban you, sorry: #14
    Mar 27 08:44:30 you are a coward

Times are in UTC+10.

**Comment by tonymorris** [comment] 2015-03-29 00:52
I strongly suggest starting a new IRC channel where we can have open discussion. Please suggest a way by which we can achieve this. Please do not "take a break."

**Comment by sporto** [comment] 2015-03-29 01:00
Let's please not get into the personal insults territory, words like coward, incompetent and nonsense don't belong on this discussion.

I found the ban an overreaction, but it just a product of what was agreed a long time ago, which is having a couple of people taking these decision on behalf of the group. 

We knew this was the system we had in place, so let's make something better for the future and just see this as an mistake and try to work together. There is no incompetence here, no one here is an expert on dealing with these things.

**Comment by tonymorris** [comment] 2015-03-29 01:02
Fair point.

I think an environment in which all individuals of different skill sets and demeanours can openly discuss is ideal. I don't think that has been (or will be) achieved in #polyhack. As a consequence, I suggest an alternative forum whereby all participants are comfortable in accepting openness.

I would like others' opinions in this regard.

**Comment by davidmason** [comment] 2015-03-29 01:30
I think it is too early in this process to have everyone switch to a different forum, but I also think it is too early to apply a ban so that complicates the question somewhat.

I would like to see everyone write down their perceived constraints on what is acceptable and expected here, so that it is possible to see where there is disagreement. Once that has happened it should become obvious whether there is a fundamental schism of philosophies that would justify a split, or just a communication breakdown.

Whether here or in a different forum, I think it is worth having a written code of conduct to set expectations and to ensure that the reason for any disciplinary action is clear and transparent. There would be no value in a new forum if it had no more protection against the perceived issues that have led to its inception.

**Comment by vacri** [comment] 2015-03-29 01:31
There is no such thing as a 'forum whereby all participants are comfortable in accepting openness'. As long as you have an unmoderated discussion, you will always run the risk of clashing personalities. Trying to get everyone to jump ship to a new forum would just put all the same personalities in the new place.

If you want my opinion, 'accepting openness' in your comment sounds like a euphamism for 'me getting away with abuse'. The suggestion of yours to split the forum in this context looks like an attempt to vindictively damage something where you have been hurt. Is your hurt justified? I haven't seen the conversations between you and Nicholas; it may be entirely justified. Should the forum be destroyed because two members had a falling out? No, absolutely not. It's not like this problem is rife.

This issue, while unpleasant, is a tempest in a teacup. We have a ton of people in polyhack, let's not destroy the place because two humans had a falling out. Humans do that, it's a fact of life.

**Comment by nicholasf** [comment] 2015-03-29 01:34
Hey all. 

Just spoke with Mark Wolfe. I'm out now by when I get back tonight I will.

* take myself and mark off the channel as founders and make @someoneweird founder 
* leave the channel. 

It just isn't fun anymore. Maybe this is a growth thing. For me, not losing the friendships online is a big thing, so I'll stay in touch on irc.

Cheers all! 

Nick 

Sent from my iPhone
Word

**Comment by tonymorris** [comment] 2015-03-29 01:37
@vacri It absolutely does work and has been applied on several of the projects on which I participate. There are some pre-requisites to this strategy, but be assured that it definitely works and is extremely productive for all participants, an in particular, the arbitrary one.

**Comment by tonymorris** [comment] 2015-03-29 01:39
@vacri I am not "trying to split" anything. I want a place to openly discuss technical ideas with a positive benefit, while minimising the negative impact of others. That is unlikely to occur in #polyhack. I have absolutely no interest in anything else and do not accept your charge.

**Comment by nicholasf** [comment] 2015-03-29 01:57
I emailed this through but it hasn't appeared.

So wolfeidau and I are both going to leave the channel and remove ourselves from the founder list. We will make @someoneweird a founder.

It just isn't fun anymore. The channel is too big - hopefully people will remember that I liked it when polyhack wasn't even registered.

I'll find another place to hang on irc. Keeping up the great friendships I've made online is important to me. Mark Wolfe said something similar when we spoke a while ago.

Cheers all! Peace out!

Nick

**Comment by vacri** [comment] 2015-03-29 02:38
@tonymorris That has not been my experience at all. I've seen this exact process happen a dozen times before - you'll see my first comment is talking about a particular 'cleanup' pattern, and asking people to keep their cool. It's also hard to reconcile your desire for minimal negative impact, where upthread you both call people cowards and incompetant and quote yourself calling someone a coward. You may be absolutely genuine in what you mean and I'm not out to score points or offend you, but from my reading of the commentary here, it fits the patterns I've seen before. 

But ultimately the issue is that anywhere humans gather, two people (or two cliques) will get shirty with each other. The particulars of this issue are, in the greater scheme of things, irrelevant. It will happen again in polyhack. It will happen in a new forum. It will happen in an unrelated forum. It will be happening in hundreds of forums as we speak here. If you want a diverse polyglot channel, then it kind've follows that you need a decent amount of users. And with a decent amount of users, you inevitably get these conflicts unless there's moderation/management or restrictions on how people communicate.

It's again worth noting that Polyhack is a good place, and this current issue of 'ops abuse' is not something we're seeing repeated again and again without anything being done about it. It's happened once so far, and we're talking about it in depth and trying to fix things for the future.

I am personally open to new ideas though - when you say 'pre-requisites to this strategy', what kind of things are you thinking of? Are they retro-fittable to Polyhack? Would they gel with @davidmason's proposals?

**Comment by timoxley** [comment] 2015-03-29 05:17
@deoxxa @SomeoneWeird @nicholasf @wolfeidau you are all in Melbourne, meet up in-person and talk this out please. Not worth rage-quitting the community you helped build over this.

**Comment by SomeoneWeird** [comment] 2015-03-29 06:10
I'd be happy to if others want to, set a time and place :)

**Comment by mipearson** [comment] 2015-03-29 06:36
@timoxley You are a champion and I endorse this behaviour. Nothing ever gets resolved via github issues.

**Comment by SomeoneWeird** [comment] 2015-04-08 06:10
As neither of the others have replied to timoxley, i'm going to close this. Still totally up for chatting and working stuff out though, if they want.

**Closed by SomeoneWeird** 2015-04-08 06:10 UTC

**Comment by tonymorris** [comment] 2015-04-08 06:18
I will be in Melbourne around June/July to run an introductory functional programming course. I am happy to talk to whomever about whatever if it helps.

**Comment by mipearson** [comment] 2015-04-21 13:25
I've changed my mind.

I've more or less stopped going on #polyhack since this occurred - partly because it's mostly dead, and partly because I just know that any interesting discussion will be derailed in to yet another ongoing, perpetual argument about how functional programming is better than whatever it is you happen to be doing right now, and how inferior everything else is.

@mwotton is at least cheerful and self-aware when this occurs, but @tonymorris, you are not. You are self-admittedly an elitist in a community that values practical programming. There is a harmful, pervasive stereotype regarding Haskell: that its adherents care not for results, but only for perfection. Be aware that your actions reinforce this stereotype.

I'll see some of you at Mark's going away, and some of you on Slack. I'm out for a while. It was fun.

(cc @nicholasf @wolfeidau @SomeoneWeird)

**Comment by kvanberendonck** [comment] 2015-04-21 13:31
The reason I actually stopped regularly going onto #polyhack was because I felt pretty out of place preferring to do daily hacking in Haskell and I could tell that there was this negative aura around FP.

O/T @mipearson I frequently see you on the bus.

**Comment by mipearson** [comment] 2015-04-21 13:38
O/T Heh. So that is you! I have been wondering.

I .. hm. I'm not sure. I think if you're coming from a pro-FP position you would see negativity, if you're coming from "I'm sick of every conversation devolving into being about FP" you would not.

It's kind of like .. if you go to a protest in Melbourne CBD, it doesn't matter what it's about, Socialist Alternative will be there, with t-shirts and placards and cards and all that. Because if we were Socialist, whatever we were protesting about wouldn't be a problem, for some reason. But all of the people who are actually there to protest about the thing - they're all "what? again? what the fuck are they doing here, this has absolutely nothing to do with the Socialist platform!"

**Comment by SomeoneWeird** [comment] 2015-04-21 14:01
I don't think there's a negative aura around FP, I think the root cause of that thinking is because when people start talking about haskell, people get into good heated arguments, which lead to walls of text (which is fine) - it just makes it hard to join mid-conversation. 

I'd also disagree with you @mipearson on the channel being dead, you just join at bad times :p

**Comment by timoxley** [comment] 2015-04-22 00:41
Conversions about the merits of FP are fine, but perhaps they could happen without all the condescending and denigrating statements about a person's technology/methodology choices. It's narrow-minded bigotry feigning as wisdom.

I've been very guilty of indulging in this kind of shitty behaviour myself but I'm working to rid myself of it. It's of no value and only puts up walls between people, while we should be pulling them down – it is #polyhack after all.

**Comment by mwotton** [comment] 2015-04-22 00:57
I think it's important that we separate criticising tech from criticising
people. If we can't talk about why a tech is a bad choice, we have nothing
to go on but tribalism, which is desperately boring. So far the only actual
personal abuse I've seen had been flowing towards @dibblego, not from him.

**Comment by timoxley** [comment] 2015-04-22 01:11
@mwotton Criticising tech is possible without making the people who use that technology feel bad.

**Comment by mipearson** [comment] 2015-04-22 01:13
Much of that criticism has not been levelled so much at the tech as the implication that those who use the tech are lazy/incompetent.

I can take a little bit of that, but it's almost constant.

For me it was more the every-discussion-is-a-fp-discussion thing.

"An athiest, a vegan, and a crossfitter walk into a bar. I only know because they told everybody within two minutes."

**Comment by kvanberendonck** [comment] 2015-04-22 01:13
I think @timoxley is right and also if I've spent a lot of time on something people criticizing the tech that it's built on overly does make me quite sad. It's like they're saying I've wasted my time, or their time is more valuable than mine, or et al.

**Comment by mipearson** [comment] 2015-04-22 01:15
Also - to Tony - EVERY tech that isn't FP is "bad", which doesn't really fit well with a community that is for polyglots. (any colour, as long as it's black)

**Comment by mipearson** [comment] 2015-04-22 01:16
Or: I've the recent change in tone exhausting, and his behaviour has made it not fun any more.

**Comment by mwotton** [comment] 2015-04-22 01:38
Well, let's look at the actual text.

[01:55:47] <dibblego> AC/DC concert tickets just went on sale.
Unfortunately, the website is written in ruby on rails. Ugh.
[01:56:23] <mp___> ?
[01:57:27] <dibblego> just full of bugs

There are many places the conversation could have gone from here. We could
have talked about why Tony thinks it's a causative relationship, we could
have enquired what bugs he actually saw, and what approach could have
avoided them, we could have pointed out a highly reliable and
fast-developed rails site that shows it's possible to build non-buggy rails
apps. There isn't anything overtly aggressive here, and no-one is mentioned
by name. Where did it actually go?

[01:57:40] <mp___> You are an elitist prick, aren't you?

@mipearson, you're a mate, but you are in the wrong here.

**Comment by mipearson** [comment] 2015-04-22 01:45
Yeah, that was my dummy spit moment. That was the point where I realised that whatever happens, whatever constructive discussion occurs, the only thing Tony brings is a universal distaste for everything he sees as "lesser". It's not fun any more.

**Comment by mwotton** [comment] 2015-04-22 02:08
I'm sorry you feel that way. I think you are wrong: Tony's done a heap of teaching in addition to building solid tech himself. I think if you look back at what he's actually said rather than what you have in your head of what he's said, it is not abusive or even particularly negative - he's just suggesting that some tools are better than others. If that's elitist, then you might as well call me an elitist too.

**Comment by radar** [comment] 2015-04-22 03:37
FTR: others thought the same way ([from here](http://logs.ryanbigg.com/polyhack?date=2015-04-20)).

```
[02:12:52] aurynn: you're not framing it as a critique. You're framing it as people who choose to use these technologies are making poor choices
```

```
[02:10:29] Andys^: sounds more like you drove a car into a river and complained the car doesn't work
...

I agree with the assessments that it felt like an attack on the language and a strong indicator that those using Rails everyday were somehow "lesser". 

On a related note: I have had to put dibblego on ignore because it makes my time in #polyhack immensely more enjoyable.

**Comment by markmandel** [comment] 2015-04-22 06:31
@mipearson @radar glad to know it's not just me.

**Comment by mdedetrich** [comment] 2015-06-24 03:01
I have to say that the main issue I have with @tonymorris is precisely what was said here https://github.com/polyhack/helloworld/issues/14#issuecomment-86754605

A lot of people claim that dibblego doesn't directly insult people, while that technically may not be true, he is indirectly condescending/insulting to people that use tech/paradigms which he doesn't agree with.

This may be more acceptable if you happen to be in something like #haskell or #ilovefp or w/e, but #polyhack is, in its mantra, designed to emphasis the use of different languages and tools.

This is why I disagree with @mwotton's argument. I feel the exact same way that @mipearson feels about @tonymorris, so its just not a few isolated incidents. I communicate daily with plenty of people (> 20) that are a fan of FP and FP related languages, and @tonymorris is the only person I have a problem with. Conversely, it seems the only people that don't have an issue with @tonymorris are ones that are heavily into FP, so they probably don't personally feel the same way about because they aren't personally exposed to such language.

Regarding going forward with the community in general. My position is this, if you end up having a non trivial amount of people having a problem with the single person, odds is, its a problem with the person. I actually think that having a small group of individuals doing actions that adhere to common sense as more effective than some really strict guidelines. More often than not, people that are problematic within the community end up try to argue their way out of the guidelines. It seems that "if enough people have an issue about the person,  than something needs to be done about the person" is the only attitude that seems to _work_
